### PR TITLE
feat: website support mobile display

### PR DESCRIPTION
**Pull request by PainterPuppets**
image
image
image
image
image

### CODE REVIEW

**Review by WhiteMinds — APPROVED** [review]

**Comment by Kirl70** [comment]
1.Not consistent with the design draft.
image

2.The text color doesn't match the design draft. If it's challenging to control the image size, please use static images for mobile.
image

3.The logo is incorrect, and the spacing, font weight, and style don't match the design draft.
image

4.Missing background image, logo orientation is incorrect. If it's difficult to control, please use a static image for mobile.
image

5.There's a lack of spacing images between each module. Please check the design draft.
image
image

6.There are new adjustments at the bottom. Please update according to the design draft.
image

**Comment by Kirl70** [comment]
1.The image's rounded corners and background image don't match the design draft.
image

2.The text needs to be aligned center.
image

**Comment by PainterPuppets** [comment]
image
Where should this be displayed in a `pagescroll` situation, at the bottom of the previous page or in the header of the next page?

image
I really can't understand this. If the scrolling animation is placed bottom the screen, and the screen scrolls up and down, so where does the animation appear when the screen scrolls? Or is there to be three animations, one for each page of `About us`?

image
This background I remember discussing was deleted? If it's added, may need to send me a `png` or `svg` image

@Kirl70

**Comment by Kirl70** [comment]
> image
> Where should this be displayed in a `pagescroll` situation, at the bottom of the previous page or in the header of the next page?
> 
> image
> I really can't understand this. If the scrolling animation is placed bottom the screen, and the screen scrolls up and down, so where does the animation appear when the screen scrolls? Or is there to be three animations, one for each page of `About us`?
> 
> image
> This background I remember discussing was deleted? If it's added, may need to send me a `png` or `svg` image
> 
> @Kirl70

1. The spacing image should be at the bottom of the previous page.
2. Use static images for mobile and ensure normal page scrolling, following the design draft.
image

3.The previously mentioned background image doesn't need to be dynamic; use a fixed background image. Please refer to the Figma file for the background image.
image

**Comment by PainterPuppets** [comment]
@Kirl70 

1 & 2: Got it, I'll make some changes later.

3 To ensure an adaptive display, the elements on the background image need to be split and given to me separately, such as these two elements and the background image without the ball

image

image

**Comment by Kirl70** [comment]
> 3 To ensure an adaptive display, the elements on the background image need to be split and given to me separately, such as these two elements and the background image without the ball

Different elements have been separated on Figma. You can click on the respective layers and export the desired resources.
image
image
image
image

**Review by Danie0918 — APPROVED** [review]

**Pull request merged**
