### PR TITLE
feat: add monitor page

### PR DESCRIPTION
**Pull request by PainterPuppets**
image
image

### CODE REVIEW

**Review by WhiteMinds — APPROVED** [review]

**Comment by Danie0918** [comment]
1. Lack of feedback on copy operation, and we need to add a post-click effect. @Kirl70 
image

2. The chart takes a few seconds to load and a loading animation needs to be added. @Kirl70 
image

3. 'History Events' not deployed. @PainterPuppets 
image

**Comment by Kirl70** [comment]
> 1. Lack of feedback on copy operation, and we need to add a post-click effect. @Kirl70
>    image

Clicking the copy icon triggers a toast notification that automatically disappears after one second.
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=30226%3A27749&mode=design&t=IIwF161rlknqgYDx-1
image


> 2. The chart takes a few seconds to load and a loading animation needs to be added. @Kirl70
>    image

Color Style:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=32401%3A31818&mode=design&t=IIwF161rlknqgYDx-1
image

Loading animation reference:
https://codepen.io/oslego/pen/XdvWmd

**Comment by PainterPuppets** [comment]
> Preview: https://status-website-delta.vercel.app/
> 
> 1. Lack of feedback on copy operation, and we need to add a post-click effect. @Kirl70
>    image
> 2. The chart takes a few seconds to load and a loading animation needs to be added. @Kirl70
>    image
> 3. 'History Events' not deployed. @PainterPuppets
>    image

It's done.

**Comment by Kirl70** [comment]
The style of the toast message doesn't match the design draft.
image
image


The spacing doesn't match the design draft:
image
image
image
image

The text color, icons, and layout don't align with the design draft, and there's a lack of specific page navigation controls:
image
image

**Comment by PainterPuppets** [comment]
> The style of the toast message doesn't match the design draft. image image
> 
> The spacing doesn't match the design draft: image image image image
> 
> The text color, icons, and layout don't align with the design draft, and there's a lack of specific page navigation controls: image image

adjusted

**Comment by Kirl70** [comment]
The hover style needs to be consistent with the previous pages. 
image
image


It has been added to the design draft.

image

**Comment by PainterPuppets** [comment]
> The hover style needs to be consistent with the previous pages. image image
> 
> It has been added to the design draft.
> 
> image

its done

**Pull request merged**
