### PR TITLE
optimize: about page

### PR DESCRIPTION
**Pull request by PainterPuppets**

### CODE REVIEW

**Comment by WhiteMinds** [comment]
Is this PR ready for review?

**Comment by Kirl70** [comment]
> > 1.The first-screen effect is inconsistent with the given parameters. image
> > Design Draft: image image
> > 2.It doesn't match the design draft. image
> > 3.The effect lacks interactivity. image
> > 4.The scrolling range is odd, resulting in a large gap that doesn't align with the design draft. image
> > Refer:[Magickbase/visual-style-guide#26](https://github.com/Magickbase/visual-style-guide/issues/26)
> 
> 1.It is indeed set according to this params, these codes are option items, can compare where there is a difference
> 
> https://github.com/Magickbase/websites/blob/276f7d7286ee6448205fe5094f5be89936026bda/packages/magickbase/public/perlin-noise/script.js#L110-L125
> 
> 2. Can describe it in detail?
> 3. The animation provided is very laggy and consumes a lot of memory, I can change to an animation for you to experience, and `Spline` animation if you want to adapt through the program needs some settings, such as setting certain variables can trigger a certain animation such as this, at present, this kind of direct autoplay without triggering animation there is no way to let the program to control the animation can only be autoplay.
> 
> 4.Because the scope of this animation is too large, containing both background and foreground content, the animation is not adaptive to the screen, so it will lead to some problems, and here you may need to split the animation into foreground and background to control separately

1. The code doesn't necessarily have to match the parameter values exactly; it's more important to adjust the code according to the effect specified by the parameters.

2. On the left is the actual webpage, and on the right is the design draft. You can observe specific differences. Additionally, the text appears based on mouse scrolling, not all displayed at once.

image

3. This animation is a frame-by-frame animation triggered by mouse scrolling.

4. What kind of adjustment details do I need to provide?

**Comment by WhiteMinds** [comment]
If this PR is in a reviewable state, please let me know.

**Comment by PainterPuppets** [comment]
Currently have optimized all the animation effects and display effects
And the footer and sidebar are intended to be shared components.
so I'm going to merge this pr before submitting a new component package

@WhiteMinds

**Pull request merged**
