### PR TITLE
fix: completes the missing dependencies

### PR DESCRIPTION
**Pull request by PainterPuppets**

### CODE REVIEW

**Review by WhiteMinds — APPROVED** [review]

**Comment by PainterPuppets** [comment]
image

Maybe it needs to be agreed upon before it can be merged. @WhiteMinds

**Comment by WhiteMinds** [comment]
> Maybe it needs to be agreed upon before it can be merged.

As long as https://neuron.magickbase.com/ is accessible and has an "approve", you can merge it directly.

I haven't merged it mainly because I'm not sure if you need to merge it at a specific time, so I'll leave it to you to merge.

**Comment by PainterPuppets** [comment]
image

I don't have merge access to this repository, so no way to merge it directly, maybe add a write access for me

**Comment by WhiteMinds** [comment]
> I don't have merge access to this repository, so no way to merge it directly, maybe add a write access for me

Okay, I forgot about that earlier.

**Pull request merged**
